---
title: "Site-level comparison"
output: html_document
---

Do we see overall relationships between canopy height and temperature, soil moisture across all sites?

# Load necessary packages
```{r}
#install.packages('pacman', repos = "http://cran.us.r-project.org")
pacman::p_load(tidyverse, broom, lubridate, gvlma, car)
```

# Read in data files
```{r}
height <- read_csv('./cleaned_data/site_height.csv')
temp <- read_csv('./cleaned_data/site_temp.csv')
soil <- read_csv('./cleaned_data/site_moisture.csv')

site_data <- read_csv('./NEON_sites/NEON_Field_Site_Metadata_20210226_0.csv') %>% 
  select(siteID, latitude, longitude, mean_elevation_m)
```

```{r}
data <- full_join(temp, soil) %>%
  full_join(., height) %>% 
  left_join(., site_data) %>% 
  mutate(siteID = factor(siteID))

print(data)
```

# Test canopy height ~ soil moisture
```{r}
ggplot(data = data, aes(x = Mean_moisture, # name the variable that goes on the x-axis
                                    y = Mean_height,  # name the variable that goes on the y-axis
                                    col = siteID)) + # name the variable to differentiate colors
  geom_point(pch = 16) +  # Graph these variables as a scatterplot
  geom_smooth(method = 'lm', aes(group=1), col = 'black', lty = 1, se=F, lwd=.5) +
  theme_minimal()
```

```{r}
soil_model <- lm(Mean_height ~ Mean_moisture, data = data)
gvlma(soil_model)
summary(soil_model)
```

# Test  canopy height ~ site temperature
```{r}
ggplot(data = data, aes(x = Mean_temp, # name the variable that goes on the x-axis
                                    y = Mean_height,  # name the variable that goes on the y-axis
                                    col = siteID)) + # name the variable to differentiate colors
  geom_point(pch = 16) +  # Graph these variables as a scatterplot
  geom_smooth(method = 'lm', aes(group=1), col = 'black', lty = 1, se=F, lwd=.5) +
  theme_minimal()
```

```{r}
temp_model <- lm(Mean_height ~ Mean_temp, data = data)
gvlma(temp_model)
summary(temp_model)
```

## Test  soil moisture ~ site temperature
```{r}
ggplot(data = data, aes(x = Mean_temp, # name the variable that goes on the x-axis
                                    y = Mean_moisture,  # name the variable that goes on the y-axis
                                    col = siteID)) + # name the variable to differentiate colors
  geom_point(pch = 16) +  # Graph these variables as a scatterplot
  geom_smooth(method = 'lm', aes(group=1), col = 'black', lty = 1, se=F, lwd=.5) +
  theme_minimal()
```

```{r}
temp_v_soil_model <- lm(Mean_moisture ~ Mean_temp, data = data)
gvlma(temp_v_soil_model)
summary(temp_v_soil_model)
```

## Elevation relationship to temperature
```{r}
ggplot(data = data, aes(x = mean_elevation_m, # name the variable that goes on the x-axis
                                    y = Mean_temp,  # name the variable that goes on the y-axis
                                    col = siteID)) + # name the variable to differentiate colors
  geom_point(pch = 16) +  # Graph these variables as a scatterplot
  geom_smooth(method = 'lm', aes(group=1), col = 'black', lty = 1, se=F, lwd=.5) +
  theme_minimal()
```

```{r}
temp_elevation_model <- lm(Mean_temp ~ mean_elevation_m, data = data)
gvlma(temp_elevation_model)
summary(temp_elevation_model)
```

