---
title: "Soil moisture data download"
output: html_document
---

# 

```{r}
#install.packages('tidyverse', repos = "http://cran.us.r-project.org")
#install.packages('neonUtilities', repos = "http://cran.us.r-project.org")

library(tidyverse)
library(neonUtilities)
```


```{r}
list2env((loadByProduct(dpID = 'DP1.00094.001', # soil moisture content
                        site = c('ABBY', 'STER', 'OAES', 'DSNY'), # Sites
                        startdate = '2016-01', # YYYY-MM
                        enddate = '2020-12',   # YYYY-MM
                        timeIndex = "30",      # 30-minute average values
                        nCores=3)),            # Run on 3 cores to accelerate; may need to modify based on your comptuter!
         .GlobalEnv)
```

```{r}
files <- mget(ls())

for (i in 1:length(files)){
  # Change the SCBI_mammals text below to indicate the name of the folder where you want to store your data
  write_csv(files[[i]], file = paste0("./raw_soil_moisture/", names(files[i]), ".csv", sep=""))
}
```

